import type { ControlAdvisorTask } from './control-v2-mock'

// Curated fixture for "Modo demo del asistente". Returns a synthetic
// list of `ControlAdvisorTask` with one example of every signal
// scenario and every `ControlAction` CTA kind. Used only by the
// testing flag wired in Settings → Desarrollo so we can step
// through every coach card and quick action without reproducing the
// preconditions in real data.
//
// Each entry mirrors what the live builders emit (id, emoji, cat,
// title, body, impact, impactRaw, urgency, confidence, dataDays,
// action). Copy is illustrative — keep it short and recognizable so
// the tester can map a card to the scenario it represents.
//
// @i18n-ignore (dev preview): toda la copy de este fixture es SOLO de
// desarrollo. Se consume únicamente cuando el "Modo demo del asistente"
// está activo (Settings → Desarrollo), un toggle gated por `__DEV__`
// que nunca se renderiza en builds de producción. Las señales reales
// que ve el usuario las construye `control-signals.ts` y ya están
// extraídas al namespace `insights:signals.*`. No se extrae esta copy
// sintética para no contaminar el bundle de traducciones con strings
// que nadie ve.
export function getAssistantDemoSignals(): ControlAdvisorTask[] {
  return [
    // ── Crisis / super-signals ──────────────────────────────────
    {
      id: 'super-perfect-storm',
      emoji: '🌪️',
      cat: 'Crisis',
      title: 'Tormenta perfecta esta semana',
      body: 'Tres patrones se alinean: gasto acelerado, racha rota y un fijo grande sin pagar. Es el momento de frenar y recalcular.',
      impact: 'Recuperar: +$28.000',
      impactRaw: 28_000,
      impactScope: 'oneTime',
      cta: 'Entrar a modo coach',
      urgency: 'alta',
      confidence: 0.95,
      dataDays: 21,
      dummyExplanation:
        'Cuando varios patrones de riesgo coinciden, el cierre de mes suele romper el presupuesto. El modo coach te guía paso a paso.',
      action: { kind: 'open-coach-mode', signalId: 'super-perfect-storm', topic: 'crisis' },
      composedOf: ['velocity', 'recovery-soft', 'fijos-ratio'],
    },
    {
      id: 'super-hidden-drain',
      emoji: '💧',
      cat: 'Fugas',
      title: 'Tres fugas chicas que suman $42.000/mes',
      body: 'Detectamos 3 patrones que se llevan plata sin que lo notes: una sub zombi, micro-cargos repetidos y un fijo subido.',
      impact: '+$42.000 por mes',
      impactRaw: 42_000,
      cta: 'Ver fugas',
      urgency: 'alta',
      confidence: 0.9,
      dataDays: 28,
      action: { kind: 'open-coach-mode', signalId: 'super-hidden-drain', topic: 'leaks' },
      composedOf: ['undetected-sub', 'small-leaks', 'price-hike'],
    },

    // ── Ciclo + tope diario ─────────────────────────────────────
    {
      id: 'payday-proximity',
      emoji: '📆',
      cat: 'Ciclo',
      title: 'Quedan 6 días con $84.000 disponibles',
      body: 'Para llegar al próximo cobro sin quedar en cero, el tope diario sugerido es $14.000 (antes $31.600).',
      impact: 'Nuevo tope diario: $14.000',
      impactRaw: 105_600,
      impactScope: 'cycle',
      cta: 'Entendido',
      urgency: 'alta',
      confidence: 1.0,
      dataDays: 24,
      action: { kind: 'dismiss', dismissId: 'payday-proximity' },
    },
    {
      id: 'start-splurge',
      emoji: '🚀',
      cat: 'Arranque',
      title: '22% del mes gastado en los primeros 3 días',
      body: 'Los primeros 3 días representan $208.000, equivalente a más de 6 días de cupo. Si el ritmo se mantiene, el resto del mes queda ajustado.',
      impact: 'Recuperar: +$113.000',
      impactRaw: 113_000,
      impactScope: 'oneTime',
      cta: 'Entendido',
      urgency: 'media',
      confidence: 0.9,
      dataDays: 4,
      action: { kind: 'dismiss', dismissId: 'start-splurge' },
    },
    {
      id: 'end-acceleration',
      emoji: '🏁',
      cat: 'Cierre',
      title: 'Los últimos 3 días vienen 60% sobre el promedio',
      body: 'Aceleraste el gasto cerca del cierre. Quedan pocos días: si bajas un 30%, llegas holgado.',
      impact: 'Recuperar: +$36.000',
      impactRaw: 36_000,
      impactScope: 'oneTime',
      cta: 'Entendido',
      urgency: 'media',
      confidence: 0.85,
      dataDays: 27,
      action: { kind: 'dismiss', dismissId: 'end-acceleration' },
    },
    {
      id: 'cycle-start',
      emoji: '🌅',
      cat: 'Ciclo',
      title: 'Ciclo nuevo: $31.600/día disponibles',
      body: 'Arrancas el ciclo con $950.000 libres después de fijos. Si te mantienes en el tope, cierras con margen.',
      impact: 'Cupo diario: $31.600',
      impactRaw: 0,
      cta: 'Entendido',
      urgency: 'baja',
      confidence: 1.0,
      dataDays: 1,
      action: { kind: 'dismiss', dismissId: 'cycle-start' },
    },

    // ── Velocidad / recuperación ────────────────────────────────
    {
      id: 'velocity',
      emoji: '⚡',
      cat: 'Velocidad',
      title: 'Tu ritmo subió 38% esta semana',
      body: 'Vas $112.000 por encima del promedio del mes. Si esto sigue, el cierre se va a complicar.',
      impact: '+$30.000 por mes',
      impactRaw: 30_000,
      cta: 'Entendido',
      urgency: 'alta',
      confidence: 0.85,
      dataDays: 21,
      action: { kind: 'dismiss', dismissId: 'velocity' },
    },
    {
      id: 'recovery-soft',
      emoji: '💪',
      cat: 'Recuperación',
      title: 'Frenaste a tiempo',
      body: 'Tras los días duros, los últimos 4 cerraron por debajo del cupo. Mantén el ritmo.',
      impact: 'Ahorro: +$18.000',
      impactRaw: 18_000,
      impactScope: 'oneTime',
      cta: 'Listo',
      urgency: 'baja',
      confidence: 0.8,
      dataDays: 21,
      action: { kind: 'dismiss', dismissId: 'recovery-soft' },
    },

    // ── Categorías ───────────────────────────────────────────────
    {
      id: 'cat-acceleration-ocio',
      emoji: '🎬',
      cat: 'Ocio',
      title: 'Ocio se duplicó esta semana',
      body: 'Pasó de $24.000/sem a $52.000/sem. Si vuelves al promedio, el mes cierra con margen.',
      impact: '+$28.000 por mes',
      impactRaw: 28_000,
      cta: 'Ver gastos de Ocio',
      urgency: 'media',
      confidence: 0.85,
      dataDays: 21,
      action: {
        kind: 'open-expenses-filtered',
        filter: { categoryId: 'cat-ocio', dateRange: 'last-7' },
      },
    },
    {
      id: 'cat-cap-breach-supermercado',
      emoji: '🛒',
      cat: 'Supermercado',
      title: 'Pasaste el tope de Supermercado',
      body: 'Ya gastaste $96.000 contra un tope de $80.000. Quedan 12 días en el ciclo.',
      impact: '+$16.000 sobre tope',
      impactRaw: 16_000,
      cta: 'Ver detalle',
      urgency: 'alta',
      confidence: 1.0,
      dataDays: 18,
      action: {
        kind: 'open-expenses-filtered',
        filter: { categoryId: 'cat-supermercado' },
      },
    },
    {
      id: 'cat-dominance-restaurantes',
      emoji: '🍽️',
      cat: 'Restaurantes',
      title: 'Restaurantes lidera con 32% del gasto',
      body: 'Es la categoría que más pesa este mes. Una semana sin pedidos te ahorra ~$24.000.',
      impact: '+$24.000 por mes',
      impactRaw: 24_000,
      cta: 'Entendido',
      urgency: 'baja',
      confidence: 0.85,
      dataDays: 21,
      action: { kind: 'dismiss', dismissId: 'cat-dominance-cat-resto' },
    },
    {
      id: 'cat-win-transporte',
      emoji: '🏆',
      cat: 'Transporte',
      title: 'Transporte 22% por debajo del mes pasado',
      body: 'Bajaste de $48.000 a $37.500. Sigue así.',
      impact: 'Ahorro: $10.500',
      impactRaw: 10_500,
      impactScope: 'oneTime',
      cta: 'Genial',
      urgency: 'baja',
      confidence: 0.9,
      dataDays: 21,
      action: { kind: 'dismiss', dismissId: 'cat-win' },
    },

    // ── Suscripciones / fijos ───────────────────────────────────
    {
      id: 'undetected-sub',
      emoji: '🧟',
      cat: 'Suscripciones',
      title: 'Disney+ lleva 2 meses sin uso',
      body: 'Pagas $4.200/mes. Si lo cancelas, te ahorras $50.400 al año.',
      impact: '+$4.200 por mes',
      impactRaw: 4_200,
      cta: 'Ver fijos',
      urgency: 'alta',
      confidence: 1.0,
      dataDays: 60,
      action: { kind: 'navigate', route: '/(app)/(tabs)/fixed-expenses' },
    },
    {
      id: 'price-hike-edenor',
      emoji: '⚡',
      cat: 'Servicios',
      title: 'Edenor subió 16%',
      body: 'Pasó de $28.000 a $32.500. Toca para abrirlo y ajustar el monto del fijo.',
      impact: '−$4.500 por mes',
      impactRaw: 4_500,
      cta: 'Ajustar fijo',
      urgency: 'media',
      confidence: 1.0,
      dataDays: 90,
      action: { kind: 'open-fixed-expense', fixedExpenseId: 'demo-edenor' },
    },
    {
      id: 'fijos-ratio',
      emoji: '🏠',
      cat: 'Fijos',
      title: 'Tus fijos ya son el 57% de tu ingreso',
      body: 'Por encima del 50% empieza a ser difícil ahorrar. Revisa los compromisos recurrentes.',
      impact: 'Ratio: 57%',
      impactRaw: 0,
      cta: 'Lo tengo',
      urgency: 'media',
      confidence: 1.0,
      dataDays: 30,
      action: { kind: 'dismiss', dismissId: 'fijos-ratio' },
    },

    // ── Hábitos / patrones ──────────────────────────────────────
    {
      id: 'small-leaks',
      emoji: '💧',
      cat: 'Microgastos',
      title: '14 micro-cargos sumaron $18.400',
      body: 'Compras chicas (snacks, peajes, kioskos) que no aparecen en tu radar pero suman.',
      impact: '+$18.400 por mes',
      impactRaw: 18_400,
      cta: 'Ver detalle',
      urgency: 'baja',
      confidence: 0.8,
      dataDays: 21,
      action: {
        kind: 'open-expenses-filtered',
        filter: { priceMax: 5000, dateRange: 'last-7' },
      },
    },
    {
      id: 'night-impulse',
      emoji: '🌙',
      cat: 'Impulso nocturno',
      title: '4 compras impulsivas después de las 22h',
      body: 'Ese pico de fin de día sumó $14.200 esta semana. Probablemente apps de delivery.',
      impact: '+$14.200 por semana',
      impactRaw: 14_200,
      cta: 'Lo tengo',
      urgency: 'baja',
      confidence: 0.7,
      dataDays: 21,
      action: { kind: 'dismiss', dismissId: 'night-impulse' },
    },
    {
      id: 'weekly-pattern',
      emoji: '📅',
      cat: 'Patrón semanal',
      title: 'Los viernes gastas 2,1× el promedio',
      body: 'Tu día de mayor gasto cae sistemáticamente los viernes.',
      impact: 'Insight',
      impactRaw: 0,
      cta: 'Lo tengo',
      urgency: 'baja',
      confidence: 0.85,
      dataDays: 28,
      action: { kind: 'dismiss', dismissId: 'weekly-pattern' },
    },
    {
      id: 'high-single-expense',
      emoji: '💸',
      cat: 'Gasto único',
      title: 'Gasto de $98.000 ayer',
      body: 'Un solo movimiento se llevó 3,1 días de cupo. Confirma que sea recurrente o lo veas como gasto único.',
      impact: 'Revisar',
      impactRaw: 98_000,
      impactScope: 'oneTime',
      cta: 'Abrir el gasto',
      urgency: 'media',
      confidence: 1.0,
      dataDays: 21,
      action: {
        kind: 'open-expenses-filtered',
        filter: { focusExpenseId: 'demo-expense-1', dateRange: 'today' },
      },
    },
    {
      id: 'duplicate-merchant',
      emoji: '🔁',
      cat: 'Posible duplicado',
      title: '2 cargos iguales en Mercadona',
      body: 'Dos movimientos de $24.300 con 11 minutos de diferencia. Puede ser un duplicado del POS.',
      impact: 'Revisar: $24.300',
      impactRaw: 24_300,
      impactScope: 'oneTime',
      cta: 'Ver gastos',
      urgency: 'media',
      confidence: 0.85,
      dataDays: 21,
      action: {
        kind: 'open-expenses-filtered',
        filter: { dateRange: 'last-7' },
      },
    },

    // ── Pronósticos ─────────────────────────────────────────────
    {
      id: 'positive-forecast',
      emoji: '🎯',
      cat: 'Pronóstico',
      title: 'Vas a cerrar con $74.000 de excedente',
      body: 'Si mantienes el ritmo actual hasta el cierre, te sobra plata. Puedes mandarla directo a tu meta.',
      impact: '+$74.000 al cierre',
      impactRaw: 74_000,
      impactScope: 'oneTime',
      cta: 'Aportar a la meta',
      urgency: 'baja',
      confidence: 0.85,
      dataDays: 21,
      action: {
        kind: 'quick-savings-contribution',
        amount: 74_000,
        dismissId: 'positive-forecast',
      },
    },
    {
      id: 'forecast-tomorrow',
      emoji: '⛅',
      cat: 'Pronóstico',
      title: 'Mañana hay riesgo de pasarte',
      body: 'Por tu patrón histórico, el sábado sueles gastar el doble. Empieza con margen.',
      impact: 'Riesgo: medio',
      impactRaw: 0,
      cta: 'Listo',
      urgency: 'baja',
      confidence: 0.7,
      dataDays: 21,
      action: { kind: 'dismiss', dismissId: 'forecast-tomorrow' },
    },
    {
      id: 'forecast-storm-week',
      emoji: '🌧️',
      cat: 'Pronóstico',
      title: 'Semana ajustada por delante',
      body: 'Confluyen tu día caro de la semana, un fijo grande y un cumpleaños recurrente. Planea con margen.',
      impact: 'Reservar: $52.000',
      impactRaw: 52_000,
      impactScope: 'oneTime',
      cta: 'Entendido',
      urgency: 'media',
      confidence: 0.75,
      dataDays: 28,
      action: { kind: 'dismiss', dismissId: 'forecast-storm-week' },
    },
    {
      id: 'forecast-payday-gap',
      emoji: '⏳',
      cat: 'Pronóstico',
      title: 'Te quedas sin cupo 3 días antes del cobro',
      body: 'Al ritmo actual el cupo se acaba el día 27 y cobras el 30.',
      impact: 'Recortar: $24.000',
      impactRaw: 24_000,
      impactScope: 'cycle',
      cta: 'Entendido',
      urgency: 'alta',
      confidence: 0.8,
      dataDays: 21,
      action: { kind: 'dismiss', dismissId: 'forecast-payday-gap' },
    },

    // ── Ahorro / meta ────────────────────────────────────────────
    {
      id: 'savings-feasibility',
      emoji: '🎯',
      cat: 'Meta',
      title: 'La meta requiere $42.000/mes — vas en $26.000',
      body: 'Te falta sumar $16.000/mes para llegar al objetivo a tiempo. Ajusta la meta o el aporte.',
      impact: 'Brecha: $16.000/mes',
      impactRaw: 16_000,
      cta: 'Ajustar meta',
      urgency: 'media',
      confidence: 0.95,
      dataDays: 60,
      action: { kind: 'open-savings-goal' },
    },
    {
      id: 'savings-overachievement',
      emoji: '🚀',
      cat: 'Meta',
      title: 'Vas 28% adelantado en tu meta',
      body: 'A este ritmo cumples antes. Considera subir el objetivo.',
      impact: 'Adelanto: $58.000',
      impactRaw: 58_000,
      impactScope: 'oneTime',
      cta: 'Subir meta',
      urgency: 'baja',
      confidence: 0.9,
      dataDays: 90,
      action: { kind: 'open-savings-goal' },
    },
    {
      id: 'savings-milestone',
      emoji: '🏁',
      cat: 'Meta',
      title: 'Llegaste al 50% de tu meta',
      body: 'Mitad de camino. Faltan $310.000 para el objetivo.',
      impact: '50% completado',
      impactRaw: 0,
      cta: 'Felicidades',
      urgency: 'baja',
      confidence: 1.0,
      dataDays: 90,
      action: { kind: 'dismiss', dismissId: 'savings-milestone' },
    },

    // ── Hogar (multi-miembro) ───────────────────────────────────
    {
      id: 'member-imbalance',
      emoji: '⚖️',
      cat: 'Hogar',
      title: 'Mariana cargó el 78% del mes',
      body: 'El gasto familiar quedó muy desbalanceado este mes. Puedes enviarle un aviso amistoso.',
      impact: 'Balance: 78/22',
      impactRaw: 0,
      cta: 'Enviar aviso',
      urgency: 'baja',
      confidence: 0.9,
      dataDays: 28,
      action: {
        kind: 'send-member-warning',
        targetUserId: 'demo-member-id',
        message: 'Llevas más del 75% del gasto este mes — coordinemos los próximos.',
      },
    },

    // ── Datos / configuración ───────────────────────────────────
    {
      id: 'income-missing',
      emoji: '💼',
      cat: 'Configuración',
      title: 'Falta tu ingreso mensual',
      body: 'Sin ingreso configurado no podemos calcular el cupo diario ni pronosticar el cierre.',
      impact: 'Configurar',
      impactRaw: 0,
      cta: 'Configurar ingreso',
      urgency: 'alta',
      confidence: 1.0,
      dataDays: 0,
      action: { kind: 'open-settings-modal', modal: 'income' },
    },
    {
      id: 'income-volatility',
      emoji: '🎢',
      cat: 'Ingreso',
      title: 'Tu ingreso varió 22% en 3 meses',
      body: 'Cuando el ingreso cambia mucho, conviene tener un colchón de 1 mes en alcancía.',
      impact: 'Variabilidad: 22%',
      impactRaw: 0,
      cta: 'Lo tengo',
      urgency: 'media',
      confidence: 0.85,
      dataDays: 90,
      action: { kind: 'dismiss', dismissId: 'income-volatility' },
    },
    {
      id: 'data-gap',
      emoji: '📉',
      cat: 'Datos',
      title: '4 días sin registros',
      body: 'Si dejaste de cargar, los pronósticos se ven afectados. Carga lo que falta o marca esos días.',
      impact: 'Datos incompletos',
      impactRaw: 0,
      cta: 'Entendido',
      urgency: 'baja',
      confidence: 1.0,
      dataDays: 17,
      action: { kind: 'dismiss', dismissId: 'data-gap' },
    },

    // ── Causalidades ────────────────────────────────────────────
    {
      id: 'causal-friday-cascade',
      emoji: '🔗',
      cat: 'Patrón causal',
      title: 'Cascada del viernes a sábado',
      body: 'Cuando el viernes te excedes, el sábado siguiente también — el patrón se ve claro en tus últimos 4 fines.',
      impact: 'Insight',
      impactRaw: 0,
      cta: 'Lo tengo',
      urgency: 'baja',
      confidence: 0.75,
      dataDays: 28,
      action: { kind: 'dismiss', dismissId: 'causal-friday-cascade' },
    },
    {
      id: 'causal-paired-impulse',
      emoji: '🔄',
      cat: 'Patrón causal',
      title: 'Compras emparejadas: Rappi + bebida',
      body: 'Casi siempre que pides Rappi cae también una compra de bebida cerca. La suma cambia el ticket promedio en 35%.',
      impact: '+35% al ticket',
      impactRaw: 0,
      cta: 'Lo tengo',
      urgency: 'baja',
      confidence: 0.7,
      dataDays: 28,
      action: { kind: 'dismiss', dismissId: 'causal-paired-impulse' },
    },
    {
      id: 'causal-stress-spending',
      emoji: '🧠',
      cat: 'Patrón causal',
      title: 'Días con muchos gastos chicos = noches con uno grande',
      body: 'En 4 de 5 casos, los días con 6+ movimientos cierran con una compra única alta. Probablemente tensión que se libera al final.',
      impact: 'Insight',
      impactRaw: 0,
      cta: 'Lo tengo',
      urgency: 'baja',
      confidence: 0.65,
      dataDays: 28,
      action: { kind: 'dismiss', dismissId: 'causal-stress-spending' },
    },

    // ── Ajustes (modales directos sobre la vista actual) ────────
    {
      id: 'tune-payday',
      emoji: '🗓️',
      cat: 'Configuración',
      title: 'Confirma tu día de cobro',
      body: 'Detectamos que tu sueldo cae cerca del día 5, pero la app está calibrada al día 1. Ajustarlo mejora el cupo diario y los pronósticos.',
      impact: 'Ajuste de ciclo',
      impactRaw: 0,
      cta: 'Ajustar día de cobro',
      urgency: 'media',
      confidence: 0.9,
      dataDays: 60,
      action: { kind: 'open-settings-modal', modal: 'payday' },
    },
    {
      id: 'tune-savings-percent',
      emoji: '🎯',
      cat: 'Meta',
      title: 'Sube el % de ahorro a 25%',
      body: 'Tu ritmo de los últimos 3 ciclos lo permite con holgura. Subir el objetivo te hace cumplir la meta antes.',
      impact: '+$32.000 por mes',
      impactRaw: 32_000,
      cta: 'Ajustar % de ahorro',
      urgency: 'baja',
      confidence: 0.85,
      dataDays: 90,
      action: { kind: 'open-settings-modal', modal: 'savings-percent' },
    },
    {
      id: 'tune-usd-rate',
      emoji: '💱',
      cat: 'Cambio',
      title: 'Tu tipo de cambio quedó desactualizado',
      body: 'La cotización guardada lleva 21 días. Actualizarla mantiene los reportes en USD precisos.',
      impact: 'Datos al día',
      impactRaw: 0,
      cta: 'Actualizar cotización',
      urgency: 'baja',
      confidence: 1.0,
      dataDays: 21,
      action: { kind: 'open-settings-modal', modal: 'usd-rate' },
    },
    {
      id: 'tune-buffer',
      emoji: '🛡️',
      cat: 'Cupo diario',
      title: 'Activa un colchón sobre tu cupo',
      body: 'Sumar 10% al cupo diario te da margen los días con imprevistos sin disparar alertas.',
      impact: 'Margen extra',
      impactRaw: 0,
      cta: 'Configurar colchón',
      urgency: 'baja',
      confidence: 0.9,
      dataDays: 30,
      action: { kind: 'open-settings-modal', modal: 'buffer' },
    },
    {
      id: 'tune-display-name',
      emoji: '🪪',
      cat: 'Perfil',
      title: 'Suma tu nombre al perfil',
      body: 'Personaliza la app y permite a tu hogar ver quién registró cada movimiento.',
      impact: 'Personalización',
      impactRaw: 0,
      cta: 'Editar nombre',
      urgency: 'baja',
      confidence: 1.0,
      dataDays: 0,
      action: { kind: 'open-settings-modal', modal: 'display-name' },
    },
    {
      id: 'tune-avatar',
      emoji: '🦊',
      cat: 'Perfil',
      title: 'Elige un avatar',
      body: 'Una imagen identifica tus movimientos en la lista del hogar.',
      impact: 'Personalización',
      impactRaw: 0,
      cta: 'Elegir avatar',
      urgency: 'baja',
      confidence: 1.0,
      dataDays: 0,
      action: { kind: 'open-settings-modal', modal: 'avatar' },
    },

    // ── Informativas (read-only) ─────────────────────────────────
    // Tarjetas de check-in: no proponen una acción concreta, el CTA
    // sólo cierra la tarjeta. Las clasificamos como read-only
    // (`dismiss`) para que la lógica de despacho registre el cierre
    // y la persistencia de "ya lo vi" funcione igual que en el resto
    // de tarjetas suaves.
    {
      id: 'info-month-context',
      emoji: '📊',
      cat: 'Resumen',
      title: 'Tu ritmo este mes va parejo al promedio',
      body: 'Sin alertas activas. Esta tarjeta es solo un check-in: el ciclo va dentro de los rangos esperados según tus últimos 3 meses.',
      impact: 'Estado: estable',
      impactRaw: 0,
      cta: 'Ok',
      urgency: 'baja',
      confidence: 0.8,
      dataDays: 21,
      action: { kind: 'dismiss', dismissId: 'info-month-context' },
    },
    {
      id: 'info-data-gathering',
      emoji: '⏳',
      cat: 'Recolección',
      title: 'Estamos recolectando tu patrón',
      body: 'En 5 días más tendremos suficientes datos para empezar a generar pronósticos y detectar patrones causales.',
      impact: 'Faltan 5 días',
      impactRaw: 0,
      cta: 'Entendido',
      urgency: 'baja',
      confidence: 1.0,
      dataDays: 9,
      action: { kind: 'dismiss', dismissId: 'info-data-gathering' },
    },

    // ── Otros ────────────────────────────────────────────────────
    {
      id: 'streak-encouragement',
      emoji: '🔥',
      cat: 'Racha',
      title: 'Llevas 14 días registrando',
      body: 'Buen ritmo de seguimiento. La racha desbloquea escudos y mejora la precisión de tus pronósticos.',
      impact: 'Racha: 14 días',
      impactRaw: 0,
      cta: 'Genial',
      urgency: 'baja',
      confidence: 1.0,
      dataDays: 14,
      action: { kind: 'open-streak-sheet' },
    },
    {
      id: 'external-guide',
      emoji: '📖',
      cat: 'Lectura',
      title: 'Guía: cómo leer tu ratio de fijos',
      body: 'Un artículo corto que explica cuándo el ratio de fijos pasa de saludable a riesgoso.',
      impact: '5 min de lectura',
      impactRaw: 0,
      cta: 'Abrir guía',
      urgency: 'baja',
      confidence: 1.0,
      dataDays: 0,
      action: {
        kind: 'open-external-url',
        url: 'https://manifiesto.app/guias/ratio-fijos',
        dismissId: 'guide-fijos-ratio',
      },
    },
    {
      id: 'quick-add-fijo',
      emoji: '➕',
      cat: 'Sugerencia',
      title: 'Detectamos un cargo recurrente: Spotify $2.500',
      body: 'Aparece todos los meses. Lo agregas como fijo y se descuenta automático del mes.',
      impact: 'Visibilidad',
      impactRaw: 0,
      cta: 'Agregar como fijo',
      urgency: 'baja',
      confidence: 0.95,
      dataDays: 90,
      action: {
        kind: 'open-add-fixed-prefilled',
        amount: 2_500,
        description: 'Spotify',
      },
    },
  ]
}
