-- Avatar pack swap: replace the original 50-slug monochrome pack with
-- a 24-slug Argentine-fauna pack (yaguareté, ñandú, hornero, lobo
-- marino, capibara, cóndor, etc). Three originally-shipped slugs
-- (oveja, tucán, vaca) were removed from the pack because their source
-- artwork uses an inverse-fill construction that's incompatible with
-- the monochrome relief variant — they read as solid square slabs
-- instead of recognizable silhouettes.
-- Mirror of mobile/assets/avatars/index.ts — every slug here MUST have
-- a matching React Native Svg component at
-- mobile/assets/avatars/components/<slug>.tsx, generated by
-- scripts/generate-avatar-components.mjs.
--
-- Migration order matters:
--   1) UPSERT new slugs so the FK target exists.
--   2) Map old slugs → closest new equivalent for existing profiles.
--   3) DELETE old slugs. The FK on public.profiles.avatar_animal is
--      ON DELETE SET NULL, so any profile still referencing a removed
--      slug gets its avatar_animal nulled. The BEFORE UPDATE trigger
--      `trg_profiles_bootstrap` then reassigns a random new slug.

-- 1. Insert / refresh the new pack. ON CONFLICT keeps labels in sync if
--    the migration is re-run.
insert into public.avatar_animals (slug, label) values
  ('alpaca',         'Alpaca'),
  ('ballena',        'Ballena'),
  ('capibara',       'Capibara'),
  ('cerdo',          'Cerdo'),
  ('colibri',        'Colibri'),
  ('condor',         'Condor'),
  ('flamenco',       'Flamenco'),
  ('gallina',        'Gallina'),
  ('gato',           'Gato'),
  ('hornero',        'Hornero'),
  ('lechuza',        'Lechuza'),
  ('lobo-gris',      'Lobo gris'),
  ('lobo-marino',    'Lobo marino'),
  ('mariposa',       'Mariposa'),
  ('mono-aullador',  'Mono aullador'),
  ('nandu',          'Nandu'),
  ('nutria',         'Nutria'),
  ('pato',           'Pato'),
  ('perro',          'Perro'),
  ('pinguino',       'Pinguino'),
  ('puma',           'Puma'),
  ('tatu-carreta',   'Tatu carreta'),
  ('tortuga',        'Tortuga'),
  ('yaguarete',      'Yaguarete')
on conflict (slug) do update set label = excluded.label;

-- 2. Best-effort mapping for users who already had an avatar from the
--    old pack. The list is intentionally conservative — we only map
--    when the new slug is a clear semantic match. Anything not listed
--    here will fall through to step 3 and get a fresh random pick.
update public.profiles
   set avatar_animal = case avatar_animal
     when 'alpaca'     then 'alpaca'
     when 'butterfly'  then 'mariposa'
     when 'cat'        then 'gato'
     when 'dog'        then 'perro'
     when 'duck'       then 'pato'
     when 'husky'      then 'perro'
     when 'mianyang'   then 'alpaca'
     when 'monkey'     then 'mono-aullador'
     when 'ostrich'    then 'nandu'
     when 'owl'        then 'lechuza'
     when 'penguin'    then 'pinguino'
     when 'pig'        then 'cerdo'
     when 'rooster'    then 'gallina'
     when 'turkey'     then 'gallina'
     when 'toucan'     then 'colibri'
     when 'macaw'      then 'colibri'
     when 'whale'      then 'ballena'
     when 'manatee'    then 'ballena'
     when 'sea-ray'    then 'ballena'
     when 'tiger'      then 'yaguarete'
     when 'lion'       then 'puma'
     when 'camel'      then 'alpaca'
     else avatar_animal
   end
 where avatar_animal in (
   'alpaca','butterfly','cat','dog','duck','husky','mianyang','monkey',
   'ostrich','owl','penguin','pig','rooster','turkey','toucan','macaw',
   'whale','manatee','sea-ray','tiger','lion','camel'
 );

-- 3. Drop every slug that doesn't belong to the new pack. The FK
--    cascade nulls any remaining profile reference; the bootstrap
--    trigger then assigns a fresh random slug from the new pool.
delete from public.avatar_animals
 where slug not in (
   'alpaca','ballena','capibara','cerdo','colibri','condor','flamenco',
   'gallina','gato','hornero','lechuza','lobo-gris','lobo-marino',
   'mariposa','mono-aullador','nandu','nutria','pato','perro',
   'pinguino','puma','tatu-carreta','tortuga','yaguarete'
 );

-- 4. Defensive backfill: re-pick a random slug for anything still null
--    (e.g. profiles created without firing the bootstrap trigger, or
--    any edge case where the FK SET NULL didn't trigger reassignment).
update public.profiles p
   set avatar_animal = (
     select slug from public.avatar_animals order by random() limit 1
   )
 where p.avatar_animal is null;
