// AUTO-GENERADO por scripts/gen-category-icons.mjs — NO editar a mano.
// Íconos de categoría (stickers multicolor del owner) como PNG assets.
/* eslint-disable @typescript-eslint/no-require-imports -- los PNG entran por el require() del asset pipeline de Metro (no son imports JS). */
import type { ImageSourcePropType } from 'react-native'

export const CATEGORY_ICONS: Record<string, ImageSourcePropType> = {
  "alimentacion/cafeteria": require("../../assets/category-icons/alimentacion/cafeteria.png"),
  "alimentacion/comida-rapida": require("../../assets/category-icons/alimentacion/comida-rapida.png"),
  "alimentacion/delivery": require("../../assets/category-icons/alimentacion/delivery.png"),
  "alimentacion/panaderia": require("../../assets/category-icons/alimentacion/panaderia.png"),
  "alimentacion/postres": require("../../assets/category-icons/alimentacion/postres.png"),
  "alimentacion/salida": require("../../assets/category-icons/alimentacion/salida.png"),
  "alimentacion/supermercado": require("../../assets/category-icons/alimentacion/supermercado.png"),
  "crecimiento/brote-bebe": require("../../assets/category-icons/crecimiento/brote-bebe.png"),
  "crecimiento/marchito": require("../../assets/category-icons/crecimiento/marchito.png"),
  "crecimiento/mini-brote": require("../../assets/category-icons/crecimiento/mini-brote.png"),
  "crecimiento/pending": require("../../assets/category-icons/crecimiento/pending.png"),
  "crecimiento/recuperable": require("../../assets/category-icons/crecimiento/recuperable.png"),
  "crecimiento/recuperado": require("../../assets/category-icons/crecimiento/recuperado.png"),
  "crecimiento/semilla": require("../../assets/category-icons/crecimiento/semilla.png"),
  "cuidado-personal/calzado": require("../../assets/category-icons/cuidado-personal/calzado.png"),
  "cuidado-personal/corte-de-pelo": require("../../assets/category-icons/cuidado-personal/corte-de-pelo.png"),
  "cuidado-personal/maquillaje": require("../../assets/category-icons/cuidado-personal/maquillaje.png"),
  "cuidado-personal/perfume": require("../../assets/category-icons/cuidado-personal/perfume.png"),
  "cuidado-personal/ropa": require("../../assets/category-icons/cuidado-personal/ropa.png"),
  "deportes/actividades-fisicas": require("../../assets/category-icons/deportes/actividades-fisicas.png"),
  "deportes/objetivo": require("../../assets/category-icons/deportes/objetivo.png"),
  "deportes/paseos": require("../../assets/category-icons/deportes/paseos.png"),
  "educacion/educacion": require("../../assets/category-icons/educacion/educacion.png"),
  "educacion/libros": require("../../assets/category-icons/educacion/libros.png"),
  "educacion/utiles": require("../../assets/category-icons/educacion/utiles.png"),
  "entretenimiento/conciertos": require("../../assets/category-icons/entretenimiento/conciertos.png"),
  "entretenimiento/deportes": require("../../assets/category-icons/entretenimiento/deportes.png"),
  "entretenimiento/hobby": require("../../assets/category-icons/entretenimiento/hobby.png"),
  "entretenimiento/hotel-viajes": require("../../assets/category-icons/entretenimiento/hotel-viajes.png"),
  "entretenimiento/musica": require("../../assets/category-icons/entretenimiento/musica.png"),
  "entretenimiento/salidas-cine": require("../../assets/category-icons/entretenimiento/salidas-cine.png"),
  "entretenimiento/videojuegos": require("../../assets/category-icons/entretenimiento/videojuegos.png"),
  "extra/apps": require("../../assets/category-icons/extra/apps.png"),
  "extra/clases-virtuales": require("../../assets/category-icons/extra/clases-virtuales.png"),
  "extra/computadora": require("../../assets/category-icons/extra/computadora.png"),
  "extra/decoracion": require("../../assets/category-icons/extra/decoracion.png"),
  "extra/reparaciones": require("../../assets/category-icons/extra/reparaciones.png"),
  "extra/streaming": require("../../assets/category-icons/extra/streaming.png"),
  "extra/subscripciones": require("../../assets/category-icons/extra/subscripciones.png"),
  "finanzas/ahorro": require("../../assets/category-icons/finanzas/ahorro.png"),
  "finanzas/banco": require("../../assets/category-icons/finanzas/banco.png"),
  "finanzas/billetera": require("../../assets/category-icons/finanzas/billetera.png"),
  "finanzas/bono": require("../../assets/category-icons/finanzas/bono.png"),
  "finanzas/bonus": require("../../assets/category-icons/finanzas/bonus.png"),
  "finanzas/cajero": require("../../assets/category-icons/finanzas/cajero.png"),
  "finanzas/deuda": require("../../assets/category-icons/finanzas/deuda.png"),
  "finanzas/impuestos": require("../../assets/category-icons/finanzas/impuestos.png"),
  "finanzas/inversiones": require("../../assets/category-icons/finanzas/inversiones.png"),
  "finanzas/seguros": require("../../assets/category-icons/finanzas/seguros.png"),
  "finanzas/tarjeta-de-credito": require("../../assets/category-icons/finanzas/tarjeta-de-credito.png"),
  "finanzas/transferencia": require("../../assets/category-icons/finanzas/transferencia.png"),
  "finanzas/venta": require("../../assets/category-icons/finanzas/venta.png"),
  "frecuencias/anual": require("../../assets/category-icons/frecuencias/anual.png"),
  "frecuencias/cuotas": require("../../assets/category-icons/frecuencias/cuotas.png"),
  "frecuencias/mensual": require("../../assets/category-icons/frecuencias/mensual.png"),
  "frecuencias/quincenal": require("../../assets/category-icons/frecuencias/quincenal.png"),
  "frecuencias/semanal": require("../../assets/category-icons/frecuencias/semanal.png"),
  "frecuencias/semestral": require("../../assets/category-icons/frecuencias/semestral.png"),
  "frecuencias/trimestral": require("../../assets/category-icons/frecuencias/trimestral.png"),
  "metas/anillo": require("../../assets/category-icons/metas/anillo.png"),
  "metas/objetivo": require("../../assets/category-icons/metas/objetivo.png"),
  "metas/playa": require("../../assets/category-icons/metas/playa.png"),
  "metas/terreno": require("../../assets/category-icons/metas/terreno.png"),
  "metas/turismo": require("../../assets/category-icons/metas/turismo.png"),
  "salud/dentista": require("../../assets/category-icons/salud/dentista.png"),
  "salud/farmacia": require("../../assets/category-icons/salud/farmacia.png"),
  "salud/gimnasio": require("../../assets/category-icons/salud/gimnasio.png"),
  "salud/medico": require("../../assets/category-icons/salud/medico.png"),
  "salud/oculista": require("../../assets/category-icons/salud/oculista.png"),
  "servicios-general/donaciones": require("../../assets/category-icons/servicios-general/donaciones.png"),
  "servicios-general/hardware": require("../../assets/category-icons/servicios-general/hardware.png"),
  "servicios-general/mascotas": require("../../assets/category-icons/servicios-general/mascotas.png"),
  "servicios-general/otros": require("../../assets/category-icons/servicios-general/otros.png"),
  "servicios-general/regalos": require("../../assets/category-icons/servicios-general/regalos.png"),
  "servicios-general/servicios": require("../../assets/category-icons/servicios-general/servicios.png"),
  "tecnologia/accesorios": require("../../assets/category-icons/tecnologia/accesorios.png"),
  "tecnologia/celular": require("../../assets/category-icons/tecnologia/celular.png"),
  "tecnologia/fotografia": require("../../assets/category-icons/tecnologia/fotografia.png"),
  "tecnologia/nube": require("../../assets/category-icons/tecnologia/nube.png"),
  "transporte/automovil": require("../../assets/category-icons/transporte/automovil.png"),
  "transporte/avion": require("../../assets/category-icons/transporte/avion.png"),
  "transporte/bicicleta": require("../../assets/category-icons/transporte/bicicleta.png"),
  "transporte/combustible": require("../../assets/category-icons/transporte/combustible.png"),
  "transporte/metro-subte": require("../../assets/category-icons/transporte/metro-subte.png"),
  "transporte/parking": require("../../assets/category-icons/transporte/parking.png"),
  "transporte/taxi": require("../../assets/category-icons/transporte/taxi.png"),
  "transporte/transporte-publico": require("../../assets/category-icons/transporte/transporte-publico.png"),
  "vivienda/agua": require("../../assets/category-icons/vivienda/agua.png"),
  "vivienda/electricidad": require("../../assets/category-icons/vivienda/electricidad.png"),
  "vivienda/gas": require("../../assets/category-icons/vivienda/gas.png"),
  "vivienda/hipoteca": require("../../assets/category-icons/vivienda/hipoteca.png"),
  "vivienda/internet": require("../../assets/category-icons/vivienda/internet.png"),
  "vivienda/limpieza": require("../../assets/category-icons/vivienda/limpieza.png"),
  "vivienda/vivienda": require("../../assets/category-icons/vivienda/vivienda.png"),
}

export type CategoryIconKey = keyof typeof CATEGORY_ICONS

export const CATEGORY_ICON_KEYS = [
  "alimentacion/cafeteria",
  "alimentacion/comida-rapida",
  "alimentacion/delivery",
  "alimentacion/panaderia",
  "alimentacion/postres",
  "alimentacion/salida",
  "alimentacion/supermercado",
  "crecimiento/brote-bebe",
  "crecimiento/marchito",
  "crecimiento/mini-brote",
  "crecimiento/pending",
  "crecimiento/recuperable",
  "crecimiento/recuperado",
  "crecimiento/semilla",
  "cuidado-personal/calzado",
  "cuidado-personal/corte-de-pelo",
  "cuidado-personal/maquillaje",
  "cuidado-personal/perfume",
  "cuidado-personal/ropa",
  "deportes/actividades-fisicas",
  "deportes/objetivo",
  "deportes/paseos",
  "educacion/educacion",
  "educacion/libros",
  "educacion/utiles",
  "entretenimiento/conciertos",
  "entretenimiento/deportes",
  "entretenimiento/hobby",
  "entretenimiento/hotel-viajes",
  "entretenimiento/musica",
  "entretenimiento/salidas-cine",
  "entretenimiento/videojuegos",
  "extra/apps",
  "extra/clases-virtuales",
  "extra/computadora",
  "extra/decoracion",
  "extra/reparaciones",
  "extra/streaming",
  "extra/subscripciones",
  "finanzas/ahorro",
  "finanzas/banco",
  "finanzas/billetera",
  "finanzas/bono",
  "finanzas/bonus",
  "finanzas/cajero",
  "finanzas/deuda",
  "finanzas/impuestos",
  "finanzas/inversiones",
  "finanzas/seguros",
  "finanzas/tarjeta-de-credito",
  "finanzas/transferencia",
  "finanzas/venta",
  "frecuencias/anual",
  "frecuencias/cuotas",
  "frecuencias/mensual",
  "frecuencias/quincenal",
  "frecuencias/semanal",
  "frecuencias/semestral",
  "frecuencias/trimestral",
  "metas/anillo",
  "metas/objetivo",
  "metas/playa",
  "metas/terreno",
  "metas/turismo",
  "salud/dentista",
  "salud/farmacia",
  "salud/gimnasio",
  "salud/medico",
  "salud/oculista",
  "servicios-general/donaciones",
  "servicios-general/hardware",
  "servicios-general/mascotas",
  "servicios-general/otros",
  "servicios-general/regalos",
  "servicios-general/servicios",
  "tecnologia/accesorios",
  "tecnologia/celular",
  "tecnologia/fotografia",
  "tecnologia/nube",
  "transporte/automovil",
  "transporte/avion",
  "transporte/bicicleta",
  "transporte/combustible",
  "transporte/metro-subte",
  "transporte/parking",
  "transporte/taxi",
  "transporte/transporte-publico",
  "vivienda/agua",
  "vivienda/electricidad",
  "vivienda/gas",
  "vivienda/hipoteca",
  "vivienda/internet",
  "vivienda/limpieza",
  "vivienda/vivienda"
] as const
